### PR TITLE
Rename and linting

### PR DESCRIPTION
**Pull request by mlrawlings**

### CODE REVIEW

**Comment by mlrawlings** [comment]
@philidem I haven't run this yet, but am I correct in assuming that `marko-starter test-app` should be `marko-starter new test-app`?

**Comment by mlrawlings** [comment]
Also, thoughts on `new` vs `create`?

**Comment by austinkelleher** [comment]
Just throwing out a few existing examples:

[Ember](https://github.com/ember-cli/ember-cli#create-a-new-project): `ember new test-app`
[React](https://github.com/facebookincubator/create-react-app#tldr): `create-react-app test-app`
[Angular](https://github.com/angular/angular-cli#generating-and-serving-an-angular2-project-via-a-development-server): `ng new test-app`

**Comment by philidem** [comment]
Yes, it is currently `marko-starter new test-app`. I would prefer to use `marko-starter create test-app` though.

**Comment by philidem** [comment]
Hmm, maybe `new` is more prevalent based on Austin's examples.

**Pull request merged**
